# Generated by Django 5.2.5 on 2025-08-16 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('broken', models.CharField(max_length=10)),
                ('asset', models.CharField(max_length=10)),
                ('entry', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=10)),
                ('active', models.CharField(max_length=1)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
