# Generated by Django 5.2.5 on 2025-08-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signal',
            new_name='Signals',
        ),
    ]
